CREATE TABLE T_USU_SOLCADASTRO (
  USU_USUARIO_CODIGO       BIGINT AUTO_INCREMENT PRIMARY KEY,
  USU_USUARIO_NOME         VARCHAR(150) NOT NULL,
  USU_USUARIO_CPF 		   CHAR(11) UNIQUE,
  USU_USUARIO_CIDADE       VARCHAR(255),
  USU_USUARIO_ESTADO       VARCHAR(255),
  USU_USUARIO_EMAIL        VARCHAR(255) NOT NULL,
  USU_USUARIO_TELEFONE     VARCHAR(20) NOT NULL,
  USU_USUARIO_VEICULO      VARCHAR(255),
  USU_USUARIO_SERVICO      VARCHAR(255)
);

CREATE TABLE T_SER_SERVICO (
	SER_SERVICO_COD CHAR(2) NOT NULL PRIMARY KEY,
	SER_SERVICO_DESCRICAO   VARCHAR(500) NOT NULL,
	USU_USUARIO_CODIGO	BIGINT,
    USU_USUARIO_CPF     CHAR(11),
	SER_SERVICO_DTGRAVACAO  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	SER_SERVICO_PAGO	    CHAR(1),
	SER_SERVICO_VALOR		FLOAT(8,2),
	SER_SERVICO_DESCONTO    FLOAT (3,2),
	SER_SERVICO_FINALIZADO  CHAR(1),
	FOREIGN KEY (USU_USUARIO_CODIGO) REFERENCES T_USU_SOLCADASTRO(USU_USUARIO_CODIGO),
    FOREIGN KEY (USU_USUARIO_CPF)    REFERENCES T_USU_SOLCADASTRO(USU_USUARIO_CPF)
);

CREATE TABLE T_CAD_CADASTROS (
    CADASTRO_CODIGO BIGINT AUTO_INCREMENT PRIMARY KEY,
    USU_USUARIO_CODIGO BIGINT NOT NULL,
    DATA_GRAVACAO  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VEICULO VARCHAR(255),
    SER_SERVICO_COD  CHAR(2),
    FOREIGN KEY (USU_USUARIO_CODIGO) REFERENCES T_USU_SOLCADASTRO(USU_USUARIO_CODIGO),
    FOREIGN KEY (SER_SERVICO_COD) REFERENCES T_SER_SERVICO(SER_SERVICO_COD)
);