INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Vinicius Dantas', '48465698944', 'São Paulo', 'SP', 'vincius@gmail.com', '11956564445', 'Punto T-Jet', 'Stage 02');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Breno Sousa', '56895477723', 'Belo Horizonte', 'MG', 'breno@gmail.com', '1167438885', 'VW Nivus', 'Stage 01');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Carlos Sousa', '45475236326', 'Belo Horizonte', 'MG', 'carlos@gmail.com', '11965784441', 'BMW 320i', 'Stage 02');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Milena Sanches', '56577741256', 'Santa Catarina', 'SC', 'milena@gmail.com', '11963632545', 'Polo GTS', 'Stage 01');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Paulo Sanches', '56577741256', 'Santa Catarina', 'SC', 'paulo@gmail.com', '11963632545', 'Polo GTS', 'Stage 01');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Danilo Martins', '78965412387', 'Rio de Janeiro', 'RJ', 'danilo@gmail.com', '21987654321', 'Chevrolet Onix', 'Stage 01');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Ricardo Silva', '12345678901', 'Porto Alegre', 'RS', 'ricardo@gmail.com', '51987654321', 'Ford Fiesta', 'Stage 02');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Juliana Costa', '98765432100', 'Salvador', 'BA', 'juliana@gmail.com', '71987654321', 'Jetta 2.0 Tsi', 'Stage 02');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Rodrigo Oliveira', '55544433322', 'Curitiba', 'PR', 'rodrigo@gmail.com', '41987654321', 'Toyota Corolla', 'Stage 01');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Fernanda Lima', '65498732100', 'Recife', 'PE', 'fernanda@gmail.com', '81987654321', 'Renault Kwid', 'Stage 01');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Pedro Oliveira', '77788899911', 'Fortaleza', 'CE', 'pedro@gmail.com', '85987654321', 'Nissan 350z', 'Stage 02');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Tatiane Santos', '88877766655', 'Manaus', 'AM', 'tatiane@gmail.com', '92987654321', 'Fiat Argo', 'Stage 01');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Gabriel Silva', '33322211144', 'Brasília', 'DF', 'gabriel@gmail.com', '61987654321', 'Volkswagen Golf Tsi', 'Stage 02');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Mariana Santos', '12131415161', 'Natal', 'RN', 'mariana@gmail.com', '84987654321', 'Honda Fit', 'Stage 01');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Lucas Oliveira', '17181920221', 'Belém', 'PA', 'lucas@gmail.com', '91987654321', 'Civic Si', 'Stage 02');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Fernando Silva', '22233344455', 'Florianópolis', 'SC', 'fernando@gmail.com', '48987654321', 'Jeep Renegade', 'Stage 01');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Beatriz Lima', '55566677788', 'João Pessoa', 'PB', 'beatriz@gmail.com', '83987654321', 'Subaru WRX STI', 'Stage 02');

INSERT INTO T_USU_SOLCADASTRO (USU_USUARIO_NOME, USU_USUARIO_CPF, USU_USUARIO_CIDADE, USU_USUARIO_ESTADO, USU_USUARIO_EMAIL, USU_USUARIO_TELEFONE, USU_USUARIO_VEICULO, USU_USUARIO_SERVICO)
VALUES ('Thiago Oliveira', '98765432100', 'São Luís', 'MA', 'thiago@gmail.com', '98987654321', 'Peugeot 208 Gt', 'Stage 02');